spring.application.name=SpringEcommerce

spring.datasource.url=jdbc:postgresql://localhost:5432/dilusha
spring.datasource.username=postgres
spring.datasource.password=DiluPostgreSQL@2026

spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false